services:
  app:
    image: backend-pages
    container_name: backend-pages
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=nhn2025!@
      - DB_NAME=db_fe
